#!/bin/bash

# A way for mybinder.org to realize it should install the jupyter lab extension
# automatically. This file does not affect anything except when mybinder.org use
# it for this specifically.
# jupyter nbextension enable --py widgetsnbextension --sys-prefix
jupyter labextension install jupyter-widgets/jupyterlab-manager@^1.0.1
jupyter labextension install jupyterlab_bokeh@^1.0.0 
jupyter labextension install jupyter-matplotlib@^0.5.0
jupyter labextension install jupyter-threejs
