name: Sync to DigitalOcean Spaces

on: 
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version number
      run: |
        VERSION=$(ls release/ | sort | tail -n1 | sed 's/\.md$//')
        DATE=$(TZ='America/Los_Angeles' date -I)
        VERSION_STR="Release: $VERSION - Date: $DATE"
        sed -i "s/Development Version/$VERSION_STR/" src/scripts/activateThebelab.js
        sed -i "s/0\.0\.0/$VERSION/" package.json
    - name: Building repo using Webpack
      run: |
        yarn install
        yarn build
    - name: Sending to DigitalOcean
      uses: LibreTexts/do-space-sync-action@master
      with:
        args: --acl public-read
      env:
        SOURCE_DIR: './build'
        DEST_DIR: 'github/ckeditor-binder-plugin'
        SPACE_NAME: ${{ secrets.Spaces_Name }}
        SPACE_REGION: ${{ secrets.Spaces_Region}}
        SPACE_ACCESS_KEY_ID: ${{ secrets.Spaces_Key }}
        SPACE_SECRET_ACCESS_KEY: ${{ secrets.Spaces_Secret }}
    # digitalocean has a 1 minute minimum TTL
    - name: Wait for DigitalOcean cache to expire
      uses: kibertoad/wait-action@1.0.1
      with:
        time: '2m'
    - name: Cloudflare Purge Cache
      uses: jakejarvis/cloudflare-purge-action@v0.3.0
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        PURGE_URLS: '["https://cdn.libretexts.net/github/ckeditor-binder-plugin/js/registerPlugin.min.js", "https://cdn.libretexts.net/github/ckeditor-binder-plugin/js/registerPlugin.min.js.map"]'
