name: Sync to DigitalOcean Spaces

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: LibreTexts/do-space-sync-action@master
      with:
        args: --acl public-read
      env:
        SOURCE_DIR: './webpack'
        DEST_DIR: 'production'
        SPACE_NAME: ${{ secrets.Spaces_Name }}
        SPACE_REGION: ${{ secrets.Spaces_Region}}
        SPACE_ACCESS_KEY_ID: ${{ secrets.Spaces_Key }}
        SPACE_SECRET_ACCESS_KEY: ${{ secrets.Spaces_Secret }}
